# Site settings
name: Matheus Cardoso
title: Matheus Cardoso | Full stack web and mobile apps developer
description: A passionate father, a truly researcher and enthusiastic software engineer. I am building web and mobile applications and a life for my son. 
url: http://matheuscas.github.io/
baseurl: ""
email: matheus.mcas@gmail.com
cover: http://matheuscas.github.io/img/og.png
logo: http://matheuscas.github.io/img/emojis/technologist.png
resume: http://matheuscas.github.io/resume.pdf
social:
  - title: email
    url: mailto:matheus.mcas@gmail.com
  - title: twitter
    url: https://twitter.com/MatheusCAS
  - title: github
    url: https://github.com/matheuscas
  - title: linkedin
    url: https://www.linkedin.com/in/matheuscardoso

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
